"""Generate docs/cli.md from the argument parser (the CLI's single source).

    python scripts/gen_cli_reference.py          # write docs/cli.md
    python scripts/gen_cli_reference.py --check  # fail if docs/cli.md is stale
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
OUT = ROOT / "docs" / "cli.md"


def render() -> str:
    from sanitizer_pro.cli import build_parser
    parser = build_parser()
    lines = [
        "# CLI reference",
        "",
        "<!-- Generated by scripts/gen_cli_reference.py from sanitizer_pro/cli.py. "
        "Do not edit by hand. -->",
        "",
        "```",
        "sanitize --input PATH --output PATH [options]",
        "sanitize diff A B [--json] [--fail-on-change]",
        "```",
        "",
    ]
    for group in parser._action_groups:
        actions = [a for a in group._group_actions if a.help != argparse.SUPPRESS]
        if not actions:
            continue
        title = {"options": "General", "optional arguments": "General",  # 3.9 name
                 "positional arguments": "Arguments"}.get(
            group.title or "", group.title or "")
        lines += [f"## {title}", "", "| Option | Default | Description |", "|---|---|---|"]
        for a in actions:
            flags = ", ".join(f"`{o}`" for o in a.option_strings) or f"`{a.dest}`"
            if a.metavar and a.nargs != 0:
                flags += f" `{a.metavar}`"
            elif a.choices and a.nargs != 0:
                flags += " `{" + ",".join(map(str, a.choices)) + "}`"
            default = a.default
            if default in (None, False, argparse.SUPPRESS) or a.nargs == 0:
                shown = ""
            else:
                shown = f"`{default}`"
            text = " ".join((a.help or "").split()).replace("|", "\\|")
            lines.append(f"| {flags} | {shown} | {text} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("docs/cli.md is out of date: run python scripts/gen_cli_reference.py",
                  file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
